baseURL = "https://sabbath-school.adventech.io/"
languageCode = "en"
title = "Sabbath School"

# very ugly, but quicker way to implement i18n using config
[params]
[params.en]
	title = "Sabbath School"
	back = "Go back"
	all = "See all"
	archive = "Lesson archive"
	lang = "🇺🇸 English"

[params.ar]
	title = "مدرسة السبت"
	back = "عُد"
	all = "اظهار الكل"
	archive = "أرشيف الدرس"
	lang = "🇸🇦 عربى"

[params.bg]
	title = "Съботно Училище"
	back = "Върни се"
	all = "Виж всички"
	archive = "Виж всички"
	lang = "🇧🇬 Български"

[params.zh]
	title = "安息日学"
	back = "回去"
	all = "查看全部"
	archive = "课程档案"
	lang = "🇨🇳 中文"

[params.da]
	title = "Sabbatsskole"
	back = "Gå tilbage"
	all = "Se alt"
	archive = "Lektion arkiv"
	lang = "🇩🇰 Dansk"

[params.fr]
	title = "École du Sabbat"
	back = "Retourner"
	all = "Voir tout"
	archive = "Archive des leçons"
	lang = "🇫🇷 Français"

[params.de]
	title = "Sabbatschule"
	back = "Geh zurück"
	all = "Alles sehen"
	archive = "Unterrichtsarchiv"
	lang = "🇩🇪 Deutsche"

[params.in]
	title = "Sekolah Sabat"
	back = "Kembali"
	all = "Lihat semua"
	archive = "Arsip pelajaran"
	lang = "🇮🇩 Bahasa Indonesia"

[params.ja]
	title = "安息日学校"
	back = "戻る"
	all = "すべてを見る"
	archive = "レッスンアーカイブ"
	lang = "🇯🇵 日本語"

[params.ko]
	title = "안식일 학교"
	back = "돌아 가기"
	all = "모두보기"
	archive = "강의 아카이브"
	lang = "🇰🇷 한국어"

[params.ms]
	title = "Sekolah Sabat"
	back = "Pergi balik"
	all = "Lihat semua"
	archive = "Arkib pelajaran"
	lang = "🇲🇾 Bahasa Melayu"

[params.no]
	title = "Sabbatsskole"
	back = "Gå tilbake"
	all = "Se alt"
	archive = "Leksjonsarkiv"
	lang = "🇳🇴 Norsk"

[params.fa]
	title = "مدرسه سبت"
	back = "برگرد"
	all = "همه را ببین"
	archive = "آرشیو درس"
	lang = "🇮🇷 فارسی"

[params.ro]
	title = "Școala de Sabat"
	back = "Întoarce-te"
	all = "Vezi toate"
	archive = "Arhiva lecțiilor"
	lang = "🇷🇴 Română"

[params.ru]
	title = "Субботняя Школа"
	back = "Назад"
	all = "Все уроки"
	archive = "Архив уроков"
	lang = "🇷🇺 Русский"

[params.sr]
	title = "Subotna škola"
	back = "Vratiti se"
	all = "Sve lekcije"
	archive = "Lekcije Arhiva"
	lang = "🇷🇸 Srpski"

[params.es]
	title = "Escuela Sabática"
	back = "Regresa"
	all = "Ver todo"
	archive = "Archivo de la lección"
	lang = "🇪🇸 Español"

[params.tr]
	title = "Sebt Okulu"
	back = "Geri dön"
	all = "Hepsini gör"
	archive = "Ders arşivi"
	lang = "🇹🇷 Türk"

[params.uk]
	title = "Суботня Школа"
	back = "Повертайся"
	all = "Бачити все"
	archive = "Архів уроку"
	lang = "🇺🇦 Українська"

[params.cs]
	title = "Sobotní škola"
	back = "Zadní"
	all = "Všechny lekce"
	archive = "Archiv hodin"
	lang = "🇨🇿 Česky"